// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { ActionBar } from '@openproject/primer-view-components-ds';

export const Default = () => <ActionBar preview="default" />;
export const Inline = () => <ActionBar preview="inline" />;
export const Sizes = () => <ActionBar preview="sizes" />;
