// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { ActionList } from '@openproject/primer-view-components-ds';

export const Default = () => <ActionList preview="default" />;
export const LeadingVisuals = () => <ActionList preview="leading_visuals" />;
export const WithManualDividers = () => <ActionList preview="with_manual_dividers" />;
export const Divider = () => <ActionList preview="divider" />;
export const Heading = () => <ActionList preview="heading" />;
export const Item = () => <ActionList preview="item" />;
export const AvatarItem = () => <ActionList preview="avatar_item" />;
export const ItemDefault = () => <ActionList preview="item_default" />;
export const ItemSizeLarge = () => <ActionList preview="item_size_large" />;
export const ItemSizeXlarge = () => <ActionList preview="item_size_xlarge" />;
export const ItemLeadingVisual = () => <ActionList preview="item_leading_visual" />;
export const ItemTrailingVisual = () => <ActionList preview="item_trailing_visual" />;
export const ItemLeadingTrailingVisual = () => <ActionList preview="item_leading_trailing_visual" />;
export const ItemWithDescription = () => <ActionList preview="item_with_description" />;
export const ItemWithDescriptionInline = () => <ActionList preview="item_with_description_inline" />;
export const ItemTrailingAction = () => <ActionList preview="item_trailing_action" />;
export const ItemDanger = () => <ActionList preview="item_danger" />;
export const ItemDisabled = () => <ActionList preview="item_disabled" />;
export const ItemWrapLabel = () => <ActionList preview="item_wrap_label" />;
export const ItemTruncateLabel = () => <ActionList preview="item_truncate_label" />;
export const ItemActive = () => <ActionList preview="item_active" />;
export const LongLabelWithTooltip = () => <ActionList preview="long_label_with_tooltip" />;
export const LongLabelWrap = () => <ActionList preview="long_label_wrap" />;
export const LongLabelTruncateNoTooltip = () => <ActionList preview="long_label_truncate_no_tooltip" />;
export const LongLabelShowTooltipWithTruncateLabel = () => <ActionList preview="long_label_show_tooltip_with_truncate_label" />;
export const Listbox = () => <ActionList preview="listbox" />;
