// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { AlphaAutoComplete } from '@openproject/primer-view-components-ds';

export const Default = () => <AlphaAutoComplete preview="default" />;
export const MoreExamples = () => <AlphaAutoComplete preview="more_examples" />;
