// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { AutoCompleteItem } from '@openproject/primer-view-components-ds';

export const Default = () => <AutoCompleteItem preview="default" />;
export const WithDescription = () => <AutoCompleteItem preview="with_description" />;
