// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { AutoComplete } from '@openproject/primer-view-components-ds';

export const Default = () => <AutoComplete preview="default" />;
export const WithSubmitButton = () => <AutoComplete preview="with_submit_button" />;
export const LeadingVisual = () => <AutoComplete preview="leading_visual" />;
export const TrailingAction = () => <AutoComplete preview="trailing_action" />;
export const FullWidth = () => <AutoComplete preview="full_width" />;
export const VisuallyHideLabel = () => <AutoComplete preview="visually_hide_label" />;
export const LeadingVisualInResults = () => <AutoComplete preview="leading_visual_in_results" />;
export const TrailingVisualInResults = () => <AutoComplete preview="trailing_visual_in_results" />;
export const WithNonVisibleLabel = () => <AutoComplete preview="with_non_visible_label" />;
export const WithIcon = () => <AutoComplete preview="with_icon" />;
export const ShowClearButton = () => <AutoComplete preview="show_clear_button" />;
export const SizeSmall = () => <AutoComplete preview="size_small" />;
export const Monospace = () => <AutoComplete preview="monospace" />;
export const Inset = () => <AutoComplete preview="inset" />;
export const NoResults = () => <AutoComplete preview="no_results" />;
export const Sizes = () => <AutoComplete preview="sizes" />;
