// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { Avatar } from '@openproject/primer-view-components-ds';

export const Default = () => <Avatar preview="default" />;
export const AsLink = () => <Avatar preview="as_link" />;
export const Sizes = () => <Avatar preview="sizes" />;
export const Shape = () => <Avatar preview="shape" />;
