// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { AvatarStack } from '@openproject/primer-view-components-ds';

export const Default = () => <AvatarStack preview="default" />;
export const MultipleAvatars = () => <AvatarStack preview="multiple_avatars" />;
export const MoreOptions = () => <AvatarStack preview="more_options" />;
