// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { Banner } from '@openproject/primer-view-components-ds';

export const Default = () => <Banner preview="default" />;
export const Dismissible = () => <Banner preview="dismissible" />;
export const WithActionButton = () => <Banner preview="with_action_button" />;
export const WithActionContent = () => <Banner preview="with_action_content" />;
export const Schemes = () => <Banner preview="schemes" />;
export const FullWidth = () => <Banner preview="full_width" />;
