// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { BaseButton } from '@openproject/primer-view-components-ds';

export const Default = () => <BaseButton preview="default" />;
export const Disabled = () => <BaseButton preview="disabled" />;
