// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { Blankslate } from '@openproject/primer-view-components-ds';

export const Default = () => <Blankslate preview="default" />;
export const WithIcon = () => <Blankslate preview="with_icon" />;
export const WithImage = () => <Blankslate preview="with_image" />;
export const Loading = () => <Blankslate preview="loading" />;
export const Description = () => <Blankslate preview="description" />;
export const PrimaryAction = () => <Blankslate preview="primary_action" />;
export const SecondaryAction = () => <Blankslate preview="secondary_action" />;
export const Full = () => <Blankslate preview="full" />;
export const InsideFlexContainer = () => <Blankslate preview="inside_flex_container" />;
export const Options = () => <Blankslate preview="options" />;
