// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { BorderBox } from '@openproject/primer-view-components-ds';

export const Default = () => <BorderBox preview="default" />;
export const HeaderWithTitle = () => <BorderBox preview="header_with_title" />;
export const RowColors = () => <BorderBox preview="row_colors" />;
export const Padding = () => <BorderBox preview="padding" />;
