// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { Box } from '@openproject/primer-view-components-ds';

export const Default = () => <Box preview="default" />;
export const Border = () => <Box preview="border" />;
export const BorderBottom = () => <Box preview="border_bottom" />;
