// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { Breadcrumbs } from '@openproject/primer-view-components-ds';

export const Default = () => <Breadcrumbs preview="default" />;
export const WithBetaTruncate = () => <Breadcrumbs preview="with_beta_truncate" />;
export const WithDeprecatedTruncate = () => <Breadcrumbs preview="with_deprecated_truncate" />;
export const WithLinkTarget = () => <Breadcrumbs preview="with_link_target" />;
export const WithLongItems = () => <Breadcrumbs preview="with_long_items" />;
