// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { Button } from '@openproject/primer-view-components-ds';

export const Default = () => <Button preview="default" />;
export const Primary = () => <Button preview="primary" />;
export const Danger = () => <Button preview="danger" />;
export const Invisible = () => <Button preview="invisible" />;
export const InvisibleAllVisuals = () => <Button preview="invisible_all_visuals" />;
export const Link = () => <Button preview="link" />;
export const AllSchemes = () => <Button preview="all_schemes" />;
export const FullWidth = () => <Button preview="full_width" />;
export const LabelWrap = () => <Button preview="label_wrap" />;
export const LinkAsButton = () => <Button preview="link_as_button" />;
export const SummaryAsButton = () => <Button preview="summary_as_button" />;
export const TrailingVisual = () => <Button preview="trailing_visual" />;
export const LeadingVisual = () => <Button preview="leading_visual" />;
export const LeadingVisualSvg = () => <Button preview="leading_visual_svg" />;
export const TrailingAction = () => <Button preview="trailing_action" />;
export const TrailingCounter = () => <Button preview="trailing_counter" />;
export const WithTooltip = () => <Button preview="with_tooltip" />;
export const Inactive = () => <Button preview="inactive" />;
export const LinkSchemeLabelWrap = () => <Button preview="link_scheme_label_wrap" />;
export const SmallSchemeOneCharacter = () => <Button preview="small_scheme_one_character" />;
