// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { ButtonGroup } from '@openproject/primer-view-components-ds';

export const Default = () => <ButtonGroup preview="default" />;
export const SplitButton = () => <ButtonGroup preview="split_button" />;
export const WithMenuButton = () => <ButtonGroup preview="with_menu_button" />;
export const IconButtons = () => <ButtonGroup preview="icon_buttons" />;
export const MultipleTags = () => <ButtonGroup preview="multiple_tags" />;
export const WithClipboardCopyButton = () => <ButtonGroup preview="with_clipboard_copy_button" />;
