// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { ButtonMarketing } from '@openproject/primer-view-components-ds';

export const Default = () => <ButtonMarketing preview="default" />;
export const LinkAsButton = () => <ButtonMarketing preview="link_as_button" />;
export const SizeVariants = () => <ButtonMarketing preview="size_variants" />;
export const Schemes = () => <ButtonMarketing preview="schemes" />;
