// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { CheckBoxGroup } from '@openproject/primer-view-components-ds';

export const Default = () => <CheckBoxGroup preview="default" />;
export const Invalid = () => <CheckBoxGroup preview="invalid" />;
export const Options = () => <CheckBoxGroup preview="options" />;
