// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { CheckBox } from '@openproject/primer-view-components-ds';

export const Default = () => <CheckBox preview="default" />;
export const Options = () => <CheckBox preview="options" />;
