// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { ClipboardCopy } from '@openproject/primer-view-components-ds';

export const Default = () => <ClipboardCopy preview="default" />;
export const Text = () => <ClipboardCopy preview="text" />;
export const Element = () => <ClipboardCopy preview="element" />;
