// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { ClipboardCopyButton } from '@openproject/primer-view-components-ds';

export const Default = () => <ClipboardCopyButton preview="default" />;
export const WithTooltip = () => <ClipboardCopyButton preview="with_tooltip" />;
