// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { CloseButton } from '@openproject/primer-view-components-ds';

export const Default = () => <CloseButton preview="default" />;
