// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { Counter } from '@openproject/primer-view-components-ds';

export const Default = () => <Counter preview="default" />;
export const WithText = () => <Counter preview="with_text" />;
export const ColorSchemes = () => <Counter preview="color_schemes" />;
export const RoundedNumber = () => <Counter preview="rounded_number" />;
