// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { Details } from '@openproject/primer-view-components-ds';

export const Default = () => <Details preview="default" />;
export const CustomButton = () => <Details preview="custom_button" />;
export const WithoutButton = () => <Details preview="without_button" />;
export const Open = () => <Details preview="open" />;
export const WithAriaLabels = () => <Details preview="with_aria_labels" />;
