// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { Dialog } from '@openproject/primer-view-components-ds';

export const Default = () => <Dialog preview="default" />;
export const LongText = () => <Dialog preview="long_text" />;
export const WithHeader = () => <Dialog preview="with_header" />;
export const WithFooter = () => <Dialog preview="with_footer" />;
export const WithForm = () => <Dialog preview="with_form" />;
export const CustomHeader = () => <Dialog preview="custom_header" />;
export const NestedDialog = () => <Dialog preview="nested_dialog" />;
export const WithTextInput = () => <Dialog preview="with_text_input" />;
export const WithAutoComplete = () => <Dialog preview="with_auto_complete" />;
export const BodyHasScrollbarOverflow = () => <Dialog preview="body_has_scrollbar_overflow" />;
export const AutofocusElement = () => <Dialog preview="autofocus_element" />;
export const LeftSide = () => <Dialog preview="left_side" />;
export const RightSide = () => <Dialog preview="right_side" />;
export const ScrollContainer = () => <Dialog preview="scroll_container" />;
export const DialogInsideOverlay = () => <Dialog preview="dialog_inside_overlay" />;
export const InitallyOpen = () => <Dialog preview="initally_open" />;
export const WithHeaderFilter = () => <Dialog preview="with_header_filter" />;
export const WithHeaderCloseButtonLabel = () => <Dialog preview="with_header_close_button_label" />;
export const WithoutHeaderCloseButtonLabel = () => <Dialog preview="without_header_close_button_label" />;
