// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { Dropdown } from '@openproject/primer-view-components-ds';

export const Default = () => <Dropdown preview="default" />;
export const Direction = () => <Dropdown preview="direction" />;
export const Options = () => <Dropdown preview="options" />;
