// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { FileTreeView } from '@openproject/primer-view-components-ds';

export const Default = () => <FileTreeView preview="default" />;
