// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { Flash } from '@openproject/primer-view-components-ds';

export const Default = () => <Flash preview="default" />;
export const ColorSchemes = () => <Flash preview="color_schemes" />;
export const MoreOptions = () => <Flash preview="more_options" />;
