// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { Forms } from '@openproject/primer-view-components-ds';

export const SingleTextFieldForm = () => <Forms preview="single_text_field_form" />;
export const MultiTextFieldForm = () => <Forms preview="multi_text_field_form" />;
export const CustomWidthFieldsForm = () => <Forms preview="custom_width_fields_form" />;
export const TextFieldAndCheckboxForm = () => <Forms preview="text_field_and_checkbox_form" />;
export const HorizontalForm = () => <Forms preview="horizontal_form" />;
export const ComposedForm = () => <Forms preview="composed_form" />;
export const SubmitButtonForm = () => <Forms preview="submit_button_form" />;
export const RadioButtonGroupForm = () => <Forms preview="radio_button_group_form" />;
export const CheckBoxGroupForm = () => <Forms preview="check_box_group_form" />;
export const ArrayCheckBoxGroupForm = () => <Forms preview="array_check_box_group_form" />;
export const SelectForm = () => <Forms preview="select_form" />;
export const ActionMenuForm = () => <Forms preview="action_menu_form" />;
export const RadioButtonWithNestedForm = () => <Forms preview="radio_button_with_nested_form" />;
export const CheckBoxWithNestedForm = () => <Forms preview="check_box_with_nested_form" />;
export const CaptionTemplateForm = () => <Forms preview="caption_template_form" />;
export const AfterContentForm = () => <Forms preview="after_content_form" />;
export const InvalidForm = () => <Forms preview="invalid_form" />;
export const MultiInputForm = () => <Forms preview="multi_input_form" />;
export const NameWithQuestionMarkForm = () => <Forms preview="name_with_question_mark_form" />;
export const ImmediateValidationForm = () => <Forms preview="immediate_validation_form" />;
export const ExampleToggleSwitchForm = () => <Forms preview="example_toggle_switch_form" />;
export const AutoCompleteForm = () => <Forms preview="auto_complete_form" />;
