// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { FormControl } from '@openproject/primer-view-components-ds';

export const Default = () => <FormControl preview="default" />;
export const Options = () => <FormControl preview="options" />;
