// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { HellipButton } from '@openproject/primer-view-components-ds';

export const Default = () => <HellipButton preview="default" />;
