// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { HiddenTextExpander } from '@openproject/primer-view-components-ds';

export const Default = () => <HiddenTextExpander preview="default" />;
