// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { IconButton } from '@openproject/primer-view-components-ds';

export const Default = () => <IconButton preview="default" />;
export const Invisible = () => <IconButton preview="invisible" />;
export const Primary = () => <IconButton preview="primary" />;
export const Danger = () => <IconButton preview="danger" />;
export const LinkAsButton = () => <IconButton preview="link_as_button" />;
export const SummaryAsButton = () => <IconButton preview="summary_as_button" />;
