// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { IncludeFragment } from '@openproject/primer-view-components-ds';

export const Default = () => <IncludeFragment preview="default" />;
