// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { Label } from '@openproject/primer-view-components-ds';

export const Default = () => <Label preview="default" />;
export const ColorSchemes = () => <Label preview="color_schemes" />;
export const Sizes = () => <Label preview="sizes" />;
export const Inline = () => <Label preview="inline" />;
