// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { Layout } from '@openproject/primer-view-components-ds';

export const Default = () => <Layout preview="default" />;
export const Gutter = () => <Layout preview="gutter" />;
export const MainWidth = () => <Layout preview="main_width" />;
export const SidebarWidth = () => <Layout preview="sidebar_width" />;
export const SidebarColumnPlacement = () => <Layout preview="sidebar_column_placement" />;
export const SidebarRowPlacement = () => <Layout preview="sidebar_row_placement" />;
export const StackingBreakpoint = () => <Layout preview="stacking_breakpoint" />;
