// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { Link } from '@openproject/primer-view-components-ds';

export const Default = () => <Link preview="default" />;
export const Tooltip = () => <Link preview="tooltip" />;
export const WithLeadingIcon = () => <Link preview="with_leading_icon" />;
export const WithTrailingIcon = () => <Link preview="with_trailing_icon" />;
export const ColorScheme = () => <Link preview="color_scheme" />;
