// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { MultiInput } from '@openproject/primer-view-components-ds';

export const Default = () => <MultiInput preview="default" />;
export const WithCaption = () => <MultiInput preview="with_caption" />;
export const VisuallyHideLabel = () => <MultiInput preview="visually_hide_label" />;
export const Disabled = () => <MultiInput preview="disabled" />;
