// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { NavList } from '@openproject/primer-view-components-ds';

export const Default = () => <NavList preview="default" />;
export const TopLevelItems = () => <NavList preview="top_level_items" />;
export const ShowMoreItem = () => <NavList preview="show_more_item" />;
export const TrailingAction = () => <NavList preview="trailing_action" />;
export const Truncate = () => <NavList preview="truncate" />;
export const LongLabelWrap = () => <NavList preview="long_label_wrap" />;
export const LongLabelShowTooltipNoTruncateLabel = () => <NavList preview="long_label_show_tooltip_no_truncate_label" />;
export const GroupLongLabelWithTooltip = () => <NavList preview="group_long_label_with_tooltip" />;
