// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { OcticonSymbols } from '@openproject/primer-view-components-ds';

export const Default = () => <OcticonSymbols preview="default" />;
