// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { OpenProjectSubHeader } from '@openproject/primer-view-components-ds';

export const Default = () => <OpenProjectSubHeader preview="default" />;
export const ActionMenuButtons = () => <OpenProjectSubHeader preview="action_menu_buttons" />;
export const DialogButtons = () => <OpenProjectSubHeader preview="dialog_buttons" />;
export const ButtonGroup = () => <OpenProjectSubHeader preview="button_group" />;
export const CustomFilterButton = () => <OpenProjectSubHeader preview="custom_filter_button" />;
export const SegmentedControl = () => <OpenProjectSubHeader preview="segmented_control" />;
export const BottomPane = () => <OpenProjectSubHeader preview="bottom_pane" />;
export const Text = () => <OpenProjectSubHeader preview="text" />;
