// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { OpenProjectFilterableTreeView } from '@openproject/primer-view-components-ds';

export const Default = () => <OpenProjectFilterableTreeView preview="default" />;
export const FormInput = () => <OpenProjectFilterableTreeView preview="form_input" />;
export const CustomSegmentedControl = () => <OpenProjectFilterableTreeView preview="custom_segmented_control" />;
export const CustomNoResultsText = () => <OpenProjectFilterableTreeView preview="custom_no_results_text" />;
export const CustomCheckboxText = () => <OpenProjectFilterableTreeView preview="custom_checkbox_text" />;
export const HideCheckbox = () => <OpenProjectFilterableTreeView preview="hide_checkbox" />;
export const HideSegmentedControl = () => <OpenProjectFilterableTreeView preview="hide_segmented_control" />;
