// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { OpenProjectFeedbackDialog } from '@openproject/primer-view-components-ds';

export const Default = () => <OpenProjectFeedbackDialog preview="default" />;
export const WithAdditionalDetails = () => <OpenProjectFeedbackDialog preview="with_additional_details" />;
export const CustomIcon = () => <OpenProjectFeedbackDialog preview="custom_icon" />;
export const WithCustomFooter = () => <OpenProjectFeedbackDialog preview="with_custom_footer" />;
export const LoadingSpinner = () => <OpenProjectFeedbackDialog preview="loading_spinner" />;
