// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { OpenProjectGridLayout } from '@openproject/primer-view-components-ds';

export const Default = () => <OpenProjectGridLayout preview="default" />;
