// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { OpenProjectDangerDialog } from '@openproject/primer-view-components-ds';

export const Default = () => <OpenProjectDangerDialog preview="default" />;
export const WithConfirmationCheckBox = () => <OpenProjectDangerDialog preview="with_confirmation_check_box" />;
export const WithFormBuilderForm = () => <OpenProjectDangerDialog preview="with_form_builder_form" />;
export const WithForm = () => <OpenProjectDangerDialog preview="with_form" />;
export const WithAdditionalDetails = () => <OpenProjectDangerDialog preview="with_additional_details" />;
export const CustomIcon = () => <OpenProjectDangerDialog preview="custom_icon" />;
export const WithFormBuilderFormTest = () => <OpenProjectDangerDialog preview="with_form_builder_form_test" />;
export const WithFormTest = () => <OpenProjectDangerDialog preview="with_form_test" />;
