// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { OpenProjectBorderBoxCollapsibleHeader } from '@openproject/primer-view-components-ds';

export const Default = () => <OpenProjectBorderBoxCollapsibleHeader preview="default" />;
export const WithCount = () => <OpenProjectBorderBoxCollapsibleHeader preview="with_count" />;
export const WithDescription = () => <OpenProjectBorderBoxCollapsibleHeader preview="with_description" />;
export const Collapsed = () => <OpenProjectBorderBoxCollapsibleHeader preview="collapsed" />;
