// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { OpenProjectAvatarWithFallback } from '@openproject/primer-view-components-ds';

export const Default = () => <OpenProjectAvatarWithFallback preview="default" />;
export const WithImage = () => <OpenProjectAvatarWithFallback preview="with_image" />;
export const FallbackInitials = () => <OpenProjectAvatarWithFallback preview="fallback_initials" />;
export const ErrorHandling404Fallback = () => <OpenProjectAvatarWithFallback preview="error_handling_404_fallback" />;
