// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { OpenProjectCollapsibleSection } from '@openproject/primer-view-components-ds';

export const Default = () => <OpenProjectCollapsibleSection preview="default" />;
export const WithAdditionalInformation = () => <OpenProjectCollapsibleSection preview="with_additional_information" />;
export const WithCaption = () => <OpenProjectCollapsibleSection preview="with_caption" />;
export const Collapsed = () => <OpenProjectCollapsibleSection preview="collapsed" />;
