// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { OpenProjectSidePanel } from '@openproject/primer-view-components-ds';

export const Default = () => <OpenProjectSidePanel preview="default" />;
export const WithComponent = () => <OpenProjectSidePanel preview="with_component" />;
export const WithActionMenu = () => <OpenProjectSidePanel preview="with_action_menu" />;
