// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { OpenProjectDragHandle } from '@openproject/primer-view-components-ds';

export const Default = () => <OpenProjectDragHandle preview="default" />;
