// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { OpenProjectFlexLayout } from '@openproject/primer-view-components-ds';

export const Default = () => <OpenProjectFlexLayout preview="default" />;
export const RowLayout = () => <OpenProjectFlexLayout preview="row_layout" />;
export const ColumnLayout = () => <OpenProjectFlexLayout preview="column_layout" />;
export const NestedLayout = () => <OpenProjectFlexLayout preview="nested_layout" />;
