// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { OpenProjectPageHeader } from '@openproject/primer-view-components-ds';

export const Default = () => <OpenProjectPageHeader preview="default" />;
export const LargeTitle = () => <OpenProjectPageHeader preview="large_title" />;
export const EditableTitle = () => <OpenProjectPageHeader preview="editable_title" />;
export const Actions = () => <OpenProjectPageHeader preview="actions" />;
export const MenuActions = () => <OpenProjectPageHeader preview="menu_actions" />;
export const DialogActions = () => <OpenProjectPageHeader preview="dialog_actions" />;
export const ZenModeButtonActions = () => <OpenProjectPageHeader preview="zen_mode_button_actions" />;
export const CreateAction = () => <OpenProjectPageHeader preview="create_action" />;
export const SingleAction = () => <OpenProjectPageHeader preview="single_action" />;
export const LeadingAction = () => <OpenProjectPageHeader preview="leading_action" />;
export const NonBoldBreadcrumbs = () => <OpenProjectPageHeader preview="non_bold_breadcrumbs" />;
export const TruncatedBreadcrumbs = () => <OpenProjectPageHeader preview="truncated_breadcrumbs" />;
export const WithoutBreadcrumbs = () => <OpenProjectPageHeader preview="without_breadcrumbs" />;
export const SkipBreadcrumbItem = () => <OpenProjectPageHeader preview="skip_breadcrumb_item" />;
export const TabNav = () => <OpenProjectPageHeader preview="tab_nav" />;
export const SegmentedControl = () => <OpenProjectPageHeader preview="segmented_control" />;
export const SegmentedControlMobileIcons = () => <OpenProjectPageHeader preview="segmented_control_mobile_icons" />;
export const Description = () => <OpenProjectPageHeader preview="description" />;
