// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { OpenProjectFeedbackMessage } from '@openproject/primer-view-components-ds';

export const Default = () => <OpenProjectFeedbackMessage preview="default" />;
export const WithCustomIcon = () => <OpenProjectFeedbackMessage preview="with_custom_icon" />;
export const WithCustomColor = () => <OpenProjectFeedbackMessage preview="with_custom_color" />;
export const LoadingSpinner = () => <OpenProjectFeedbackMessage preview="loading_spinner" />;
export const SecondaryAction = () => <OpenProjectFeedbackMessage preview="secondary_action" />;
