// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { OpenProjectInputGroup } from '@openproject/primer-view-components-ds';

export const Default = () => <OpenProjectInputGroup preview="default" />;
export const IconButton = () => <OpenProjectInputGroup preview="icon_button" />;
export const SmallInputWidth = () => <OpenProjectInputGroup preview="small_input_width" />;
export const WithCaption = () => <OpenProjectInputGroup preview="with_caption" />;
