// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { OpenProjectZenModeButton } from '@openproject/primer-view-components-ds';

export const Default = () => <OpenProjectZenModeButton preview="default" />;
