// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { OpenProjectBorderGrid } from '@openproject/primer-view-components-ds';

export const Default = () => <OpenProjectBorderGrid preview="default" />;
export const Spacious = () => <OpenProjectBorderGrid preview="spacious" />;
