// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { OpenProjectAvatarStack } from '@openproject/primer-view-components-ds';

export const Default = () => <OpenProjectAvatarStack preview="default" />;
export const WithFallbackAvatars = () => <OpenProjectAvatarStack preview="with_fallback_avatars" />;
export const MixedAvatars = () => <OpenProjectAvatarStack preview="mixed_avatars" />;
export const AlignRightWithFallbacks = () => <OpenProjectAvatarStack preview="align_right_with_fallbacks" />;
export const WithTooltipAndFallbacks = () => <OpenProjectAvatarStack preview="with_tooltip_and_fallbacks" />;
