// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { OpenProjectHeading } from '@openproject/primer-view-components-ds';

export const Default = () => <OpenProjectHeading preview="default" />;
