// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { Overlay } from '@openproject/primer-view-components-ds';

export const Default = () => <Overlay preview="default" />;
export const MenuNoHeader = () => <Overlay preview="menu_no_header" />;
export const MiddleOfPage = () => <Overlay preview="middle_of_page" />;
export const MiddleOfPageWithRelativeContainer = () => <Overlay preview="middle_of_page_with_relative_container" />;
export const InAStickyContainer = () => <Overlay preview="in_a_sticky_container" />;
