// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { Popover } from '@openproject/primer-view-components-ds';

export const Default = () => <Popover preview="default" />;
export const Large = () => <Popover preview="large" />;
export const Directions = () => <Popover preview="directions" />;
