// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { ProgressBar } from '@openproject/primer-view-components-ds';

export const Default = () => <ProgressBar preview="default" />;
export const Sizes = () => <ProgressBar preview="sizes" />;
