// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { RadioButton } from '@openproject/primer-view-components-ds';

export const Default = () => <RadioButton preview="default" />;
export const Options = () => <RadioButton preview="options" />;
