// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { RadioButtonGroup } from '@openproject/primer-view-components-ds';

export const Default = () => <RadioButtonGroup preview="default" />;
export const Invalid = () => <RadioButtonGroup preview="invalid" />;
export const Options = () => <RadioButtonGroup preview="options" />;
