// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { RelativeTime } from '@openproject/primer-view-components-ds';

export const Default = () => <RelativeTime preview="default" />;
export const MicroFormat = () => <RelativeTime preview="micro_format" />;
export const RecentTime = () => <RelativeTime preview="recent_time" />;
export const CountDownTimer = () => <RelativeTime preview="count_down_timer" />;
export const NoTitleAttribute = () => <RelativeTime preview="no_title_attribute" />;
export const LinkWithTooltip = () => <RelativeTime preview="link_with_tooltip" />;
