// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { SegmentedControl } from '@openproject/primer-view-components-ds';

export const Default = () => <SegmentedControl preview="default" />;
export const FullWidth = () => <SegmentedControl preview="full_width" />;
export const IconsAndText = () => <SegmentedControl preview="icons_and_text" />;
export const TrailingLabel = () => <SegmentedControl preview="trailing_label" />;
export const IconsOnly = () => <SegmentedControl preview="icons_only" />;
export const WithLinkAsTag = () => <SegmentedControl preview="with_link_as_tag" />;
export const WithAriaLabeledHeadings = () => <SegmentedControl preview="with_aria_labeled_headings" />;
