// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { Select } from '@openproject/primer-view-components-ds';

export const Default = () => <Select preview="default" />;
export const Options = () => <Select preview="options" />;
