// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { SelectPanel } from '@openproject/primer-view-components-ds';

export const Default = () => <SelectPanel preview="default" />;
export const LocalFetch = () => <SelectPanel preview="local_fetch" />;
export const EventuallyLocalFetch = () => <SelectPanel preview="eventually_local_fetch" />;
export const RemoteFetch = () => <SelectPanel preview="remote_fetch" />;
export const CustomLoadingLabel = () => <SelectPanel preview="custom_loading_label" />;
export const CustomLoadingDescription = () => <SelectPanel preview="custom_loading_description" />;
export const LocalFetchNoResults = () => <SelectPanel preview="local_fetch_no_results" />;
export const EventuallyLocalFetchNoResults = () => <SelectPanel preview="eventually_local_fetch_no_results" />;
export const RemoteFetchNoResults = () => <SelectPanel preview="remote_fetch_no_results" />;
export const SingleSelect = () => <SelectPanel preview="single_select" />;
export const Multiselect = () => <SelectPanel preview="multiselect" />;
export const FooterButtons = () => <SelectPanel preview="footer_buttons" />;
export const WithAvatarItems = () => <SelectPanel preview="with_avatar_items" />;
export const SelectPanelWithIconButton = () => <SelectPanel preview="select_panel_with_icon_button" />;
export const WithSubtitle = () => <SelectPanel preview="with_subtitle" />;
export const RemoteFetchInitialFailure = () => <SelectPanel preview="remote_fetch_initial_failure" />;
export const RemoteFetchFilterFailure = () => <SelectPanel preview="remote_fetch_filter_failure" />;
export const EventuallyLocalFetchInitialFailure = () => <SelectPanel preview="eventually_local_fetch_initial_failure" />;
export const SingleSelectForm = () => <SelectPanel preview="single_select_form" />;
export const RemoteFetchForm = () => <SelectPanel preview="remote_fetch_form" />;
export const MultiselectForm = () => <SelectPanel preview="multiselect_form" />;
export const ListOfLinks = () => <SelectPanel preview="list_of_links" />;
export const NoValues = () => <SelectPanel preview="no_values" />;
export const DynamicLabel = () => <SelectPanel preview="dynamic_label" />;
export const WithIcons = () => <SelectPanel preview="with_icons" />;
