// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { SkeletonBox } from '@openproject/primer-view-components-ds';

export const Default = () => <SkeletonBox preview="default" />;
