// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { State } from '@openproject/primer-view-components-ds';

export const Default = () => <State preview="default" />;
export const States = () => <State preview="states" />;
export const Sizes = () => <State preview="sizes" />;
