// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { Subhead } from '@openproject/primer-view-components-ds';

export const Default = () => <Subhead preview="default" />;
export const Danger = () => <Subhead preview="danger" />;
export const Actions = () => <Subhead preview="actions" />;
export const Spacing = () => <Subhead preview="spacing" />;
export const HeaderSize = () => <Subhead preview="header_size" />;
