// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { TabNav } from '@openproject/primer-view-components-ds';

export const Default = () => <TabNav preview="default" />;
export const WithIconsAndCounters = () => <TabNav preview="with_icons_and_counters" />;
export const WithExtra = () => <TabNav preview="with_extra" />;
