// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { TabPanels } from '@openproject/primer-view-components-ds';

export const Default = () => <TabPanels preview="default" />;
export const WithExtra = () => <TabPanels preview="with_extra" />;
