// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { TextField } from '@openproject/primer-view-components-ds';

export const Default = () => <TextField preview="default" />;
export const WithDataTarget = () => <TextField preview="with_data_target" />;
export const InputGroupLeadingButton = () => <TextField preview="input_group_leading_button" />;
export const InputGroupTrailingButton = () => <TextField preview="input_group_trailing_button" />;
export const InputGroupLeadingActionMenu = () => <TextField preview="input_group_leading_action_menu" />;
export const Sizes = () => <TextField preview="sizes" />;
export const Options = () => <TextField preview="options" />;
export const AutoCheck = () => <TextField preview="auto_check" />;
