// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { TextArea } from '@openproject/primer-view-components-ds';

export const Default = () => <TextArea preview="default" />;
export const Options = () => <TextArea preview="options" />;
