// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { TimelineItem } from '@openproject/primer-view-components-ds';

export const Default = () => <TimelineItem preview="default" />;
