// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { ToggleSwitch } from '@openproject/primer-view-components-ds';

export const Default = () => <ToggleSwitch preview="default" />;
export const Checked = () => <ToggleSwitch preview="checked" />;
export const Disabled = () => <ToggleSwitch preview="disabled" />;
export const CheckedDisabled = () => <ToggleSwitch preview="checked_disabled" />;
export const Small = () => <ToggleSwitch preview="small" />;
export const WithStatusLabelPositionEnd = () => <ToggleSwitch preview="with_status_label_position_end" />;
export const WithABadSrc = () => <ToggleSwitch preview="with_a_bad_src" />;
export const WithNoSrc = () => <ToggleSwitch preview="with_no_src" />;
export const WithCsrfToken = () => <ToggleSwitch preview="with_csrf_token" />;
export const WithBadCsrfToken = () => <ToggleSwitch preview="with_bad_csrf_token" />;
export const WithTurbo = () => <ToggleSwitch preview="with_turbo" />;
export const WithAutofocus = () => <ToggleSwitch preview="with_autofocus" />;
