// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { Tooltip } from '@openproject/primer-view-components-ds';

export const Default = () => <Tooltip preview="default" />;
export const DescriptionTooltipOnButtonWithExistingDescribedby = () => <Tooltip preview="description_tooltip_on_button_with_existing_describedby" />;
export const WithRightMostPosition = () => <Tooltip preview="with_right_most_position" />;
export const WithMultipleOnAPage = () => <Tooltip preview="with_multiple_on_a_page" />;
export const TooltipInsidePrimerOverlay = () => <Tooltip preview="tooltip_inside_primer_overlay" />;
export const TooltipWithDialogMovingFocusToInput = () => <Tooltip preview="tooltip_with_dialog_moving_focus_to_input" />;
export const TooltipN = () => <Tooltip preview="tooltip_n" />;
export const TooltipS = () => <Tooltip preview="tooltip_s" />;
export const TooltipE = () => <Tooltip preview="tooltip_e" />;
export const TooltipW = () => <Tooltip preview="tooltip_w" />;
export const TooltipSe = () => <Tooltip preview="tooltip_se" />;
export const TooltipSw = () => <Tooltip preview="tooltip_sw" />;
export const TooltipNe = () => <Tooltip preview="tooltip_ne" />;
export const TooltipNw = () => <Tooltip preview="tooltip_nw" />;
export const TooltipEnabledElements = () => <Tooltip preview="tooltip_enabled_elements" />;
