// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { TreeView } from '@openproject/primer-view-components-ds';

export const Default = () => <TreeView preview="default" />;
export const SingleSelect = () => <TreeView preview="single_select" />;
export const MultiSelect = () => <TreeView preview="multi_select" />;
export const Empty = () => <TreeView preview="empty" />;
export const LoadingFailure = () => <TreeView preview="loading_failure" />;
export const LoadingSpinner = () => <TreeView preview="loading_spinner" />;
export const LoadingSkeleton = () => <TreeView preview="loading_skeleton" />;
export const AsyncAlpha = () => <TreeView preview="async_alpha" />;
export const LeafNodePlayground = () => <TreeView preview="leaf_node_playground" />;
export const Links = () => <TreeView preview="links" />;
export const Buttons = () => <TreeView preview="buttons" />;
export const AutoExpansion = () => <TreeView preview="auto_expansion" />;
export const FormInput = () => <TreeView preview="form_input" />;
