// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { Truncate } from '@openproject/primer-view-components-ds';

export const Default = () => <Truncate preview="default" />;
export const MultipleItems = () => <Truncate preview="multiple_items" />;
export const AdvancedMultipleItems = () => <Truncate preview="advanced_multiple_items" />;
export const MaxWidths = () => <Truncate preview="max_widths" />;
