// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { UnderlinePanels } from '@openproject/primer-view-components-ds';

export const Default = () => <UnderlinePanels preview="default" />;
export const WithIconsAndCounters = () => <UnderlinePanels preview="with_icons_and_counters" />;
export const WithActions = () => <UnderlinePanels preview="with_actions" />;
