// Generated by .design-sync/generate-adapter.mjs — do not edit.
import { UnderlineNav } from '@openproject/primer-view-components-ds';

export const Default = () => <UnderlineNav preview="default" />;
export const WithIconsAndCounters = () => <UnderlineNav preview="with_icons_and_counters" />;
